<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>xiayizhou</AssemblyName>
    <Version>0.0.3-beta.3</Version>
    <Title>Xia Yi Zhou</Title>
    <Authors>Grey-Wind</Authors>
    <Company>Tsing Yi Technology</Company>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Lib.Harmony" Version="2.4.2" />
    <PackageReference Include="Pathoschild.Stardew.ModBuildConfig" Version="4.4.0" />
  </ItemGroup>

  <ItemGroup>
    <None Update="manifest.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Portraits\XiaYiZhou\assets\XiaYiZhou\XiaYiZhou_fall.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Portraits\XiaYiZhou\assets\XiaYiZhou\XiaYiZhou_marry.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Portraits\XiaYiZhou\assets\XiaYiZhou\XiaYiZhou_spring.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Portraits\XiaYiZhou\assets\XiaYiZhou\XiaYizhou_summer.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Portraits\XiaYiZhou\assets\XiaYiZhou\XiaYiZhou_winter.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Portraits\XiaYiZhou\XiaYiZhou_default.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Portraits\XiaYiZhou\assets\XiaYiZhou\" />
  </ItemGroup>

</Project>
